// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpaxxkmkstyreziipfat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwYXh4a21rc3R5cmV6aWlwZmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjE4MjYsImV4cCI6MjA2NjY5NzgyNn0._Lp3DvGcEFqxSS1P3S--rRLPXPKZ2qbGStUZh0IeycA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});